Wp 169 agent statistic stats
wazo-platform/wazo-acceptance pull request #112
Opened 2020-11-26 21:29 UTC by pc-m

2020-12-02 12:59 UTC, pc-m commented
recheck

2020-12-03 18:18 UTC, fblackburn1 requested changes

2020-12-03 18:18 UTC, fblackburn1 commented on wazo_acceptance/steps/stats.py
> +        from_=last_hour.isoformat(),
See the queue tests. But you should specify timezone:
* when jenkins run test, the UTC will be in the next day and you will have no stats
* avoid false positive on the day we change hour

2020-12-03 18:18 UTC, fblackburn1 commented on features/daily/contact-center-stats.feature
> +      |          5 |
Should we merge these two tests, to have more a workflow/acceptance tests than a specific unit test?

2020-12-03 19:31 UTC, fblackburn1 approved these changes

2020-12-03 20:26 UTC, merged