outcall permission
wazo-platform/wazo-acceptance pull request #158
Opened 2021-12-23 22:20 UTC by bloom1

2021-12-25 17:22 UTC, bloom1 commented
recheck

2022-01-03 19:43 UTC, pc-m requested changes
helpers/outcall.py

some "user" have been left instead of "outcall"

2022-01-03 19:50 UTC, bloom1 commented
> helpers/outcall.py
> 
> some "user" have been left instead of "outcall"

Is it your turn to be an eagle? :smiling_face_with_tear: 

Fixed!

2022-01-03 19:57 UTC, pc-m approved these changes

2022-01-03 23:44 UTC, merged